# go-reminders minimal container definition

# Start from scratch
FROM scratch
MAINTAINER Devin Nance <devin0072@gmail.com>

# Add the microservice
ADD monitor /usr/local/bin/monitor

# Add the content (html and templates)
#ADD html /html

